name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Installing only production dependencies..."
          npm install --production
          npm prune --production
          npm dedupe

      - name: Package the app for Lambda
        run: |
          echo "Packaging index.js and app folder into app.zip for AWS Lambda..."
          zip -r app.zip index.js app node_modules \
          -x "node_modules/.bin/**" \
          -x "node_modules/typescript/**" \
          -x "node_modules/@prisma/engines/**" \
          -x "*.md" "tests/**" "docs/**"

      - name: Unzip and check contents of app.zip
        run: |
          echo "Unzipping app.zip..."
          unzip app.zip -d extracted_app
          echo "Unzipping completed. Checking extracted_app directory size:"
          du -sh extracted_app/*
          echo "Top 10 largest node_modules folders in extracted_app:"
          du -sh extracted_app/node_modules/* | sort -rh | head -n 10

      - name: Fail if app.zip is too large
        run: |
          MAX_SIZE=50000 # 50 MB in KB
          ACTUAL_SIZE=$(du -k "app.zip" | cut -f1)
          if [ "$ACTUAL_SIZE" -gt "$MAX_SIZE" ]; then
            echo "Error: app.zip size is too large: ${ACTUAL_SIZE} KB (Max allowed: ${MAX_SIZE} KB)"
            exit 1
          fi

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Initialize Terraform with S3 backend
        run: terraform init
        working-directory: ./terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
