name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Installing all dependencies..."
          npm install
          npm dedupe

      - name: Prune devDependencies
        run: |
          echo "Removing devDependencies to reduce deployment size..."
          npm prune --production
          echo "Pruning completed."

      - name: Bundle with esbuild (Tree-Shaking & Minification)
        run: |
          echo "Bundling with esbuild..."
          npx esbuild index.js --bundle --platform=node --target=node20 --outdir=dist --external:aws-sdk
          echo "Bundling completed."

      - name: Verify bundled files
        run: |
          echo "Checking bundled files in ./dist..."
          ls -al ./dist

      - name: Package the bundled app for Lambda
        run: |
          echo "Packaging index.js and node_modules into app.zip..."
          zip -r app.zip dist/ node_modules \
          -x "*.ts" "*.md" "tests/**" "docs/**" "node_modules/.cache/**" "node_modules/aws-sdk/**" "node_modules/.bin/**"
          echo "Packaging completed."fv

      - name: Verify the size and contents of app.zip
        run: |
          echo "Checking app.zip size and contents..."
          unzip -l app.zip
          echo "Top 10 node modules"
          du -sh node_modules/* | sort -rh | head -n 10
          echo "App base folder"
          du -sh *

      - name: Fail if app.zip is too large
        run: |
          MAX_SIZE=50000 # 50 MB in KB
          ACTUAL_SIZE=$(du -k "app.zip" | cut -f1)
          if [ "$ACTUAL_SIZE" -gt "$MAX_SIZE" ]; then
            echo "Error: app.zip size is too large: ${ACTUAL_SIZE} KB (Max allowed: ${MAX_SIZE} KB)"
            exit 1
          fi

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Initialize Terraform with S3 backend
        run: terraform init
        working-directory: ./terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
