name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and package the app
        run: |
          zip -r app.zip . -x "*.git*"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Check and import S3 Bucket if exists
        run: |
          bucket_exists=$(aws s3api head-bucket --bucket narath-muni-api-bucket-v2 2>&1)
          if echo "$bucket_exists" | grep 'Not Found'; then
            echo "S3 bucket does not exist. Terraform will create it."
          else
            echo "S3 bucket exists. Importing into Terraform..."
            terraform import aws_s3_bucket.lambda_bucket narath-muni-api-bucket-v2
          fi
        working-directory: ./terraform

      - name: Check and import IAM Role if exists
        run: |
          role_exists=$(aws iam get-role --role-name lambda_exec_role 2>&1)
          if echo "$role_exists" | grep 'NoSuchEntity'; then
            echo "IAM role does not exist. Terraform will create it."
          else
            echo "IAM role exists. Importing into Terraform..."
            terraform import aws_iam_role.lambda_exec_role lambda_exec_role
          fi
        working-directory: ./terraform

      - name: Plan Terraform
        run: terraform plan
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
